common:
  arch: all
  version: 1.0.0
  copyright: Copyright 2013, 2014, 2015 Big Switch Networks
  maintainer: support@bigswitch.com

packages:
  - name: onl-docker-tools
    summary: Open Network Linux Docker Build Tools

    files:
      onlbuilder : /usr/local/bin/onlbuilder

    changelog:  Initial
